export const headerData =[
    {
        id:1,
        name:"Home",
        link:"/"
    },
    {
        id:2,
        name:"Service",
        link:"service"
    },
    {
        id:3,
        name:"Resume",
        link:"resume"
    },
    {
        id:4,
        name:"Work",
        link:"work"
    },
    {
        id:5,
        name:"Contact",
        link:"contact"
    },
]